import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

type SourceDictionaryEntry = {
  acquisitionRoutes?: Array<{
    specialConditions?: {
      area?: string
      location?: string
    }
  }>
}

type TeamcraftPlace = {
  en?: string
  ja?: string
}

type LocationTranslationEntry = {
  en: string
  ja: string
  types: Array<'area' | 'location'>
  source: 'teamcraft' | 'manual'
}

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const MANUAL_DIR = resolve(ROOT, 'src/data/reverse-search/manual')
const SOURCE_DICTIONARY_PATH = resolve(MANUAL_DIR, 'source_dictionary.json')
const OUTPUT_PATH = resolve(MANUAL_DIR, 'location_translation_dictionary.json')
const TEAMCRAFT_PLACES_URL = 'https://raw.githubusercontent.com/ffxiv-teamcraft/ffxiv-teamcraft/staging/libs/data/src/lib/json/places.json'

const MANUAL_OVERRIDES: Record<string, string> = {
  'The Endeavor': 'エンデバー号',
}

async function main() {
  const sourceDictionary = JSON.parse(await readFile(SOURCE_DICTIONARY_PATH, 'utf8')) as SourceDictionaryEntry[]

  const areaNames = new Set<string>()
  const locationNames = new Set<string>()

  for (const entry of sourceDictionary) {
    for (const route of entry.acquisitionRoutes ?? []) {
      const area = route.specialConditions?.area?.trim()
      const location = route.specialConditions?.location?.trim()

      if (area) {
        areaNames.add(area)
      }

      if (location) {
        locationNames.add(location)
      }
    }
  }

  const placesResponse = await fetch(TEAMCRAFT_PLACES_URL)

  if (!placesResponse.ok) {
    throw new Error(`Failed to fetch Teamcraft places.json: ${placesResponse.status}`)
  }

  const places = await placesResponse.json() as Record<string, TeamcraftPlace>
  const teamcraftMap = new Map<string, string>()

  for (const place of Object.values(places)) {
    if (place.en && place.ja) {
      teamcraftMap.set(place.en, place.ja)
    }
  }

  const entries = new Map<string, LocationTranslationEntry>()
  let autoGeneratedCount = 0
  let manualCount = 0
  const unmatched: string[] = []

  const register = (name: string, type: 'area' | 'location') => {
    const manualJa = MANUAL_OVERRIDES[name]
    const teamcraftJa = teamcraftMap.get(name)
    const ja = manualJa ?? teamcraftJa

    if (!ja) {
      unmatched.push(name)
      return
    }

    const source = manualJa ? 'manual' : 'teamcraft'
    const existing = entries.get(name)

    if (existing) {
      if (!existing.types.includes(type)) {
        existing.types.push(type)
      }

      return
    }

    entries.set(name, {
      en: name,
      ja,
      types: [type],
      source,
    })

    if (source === 'manual') {
      manualCount += 1
    } else {
      autoGeneratedCount += 1
    }
  }

  for (const area of [...areaNames].sort((a, b) => a.localeCompare(b))) {
    register(area, 'area')
  }

  for (const location of [...locationNames].sort((a, b) => a.localeCompare(b))) {
    register(location, 'location')
  }

  const output = [
    {
      version: 1,
      type: 'metadata',
      description: 'English to Japanese translations for fish specialConditions.area and specialConditions.location.',
      generatedAt: new Date().toISOString(),
      sources: ['Teamcraft places.json', 'manual override'],
      counts: {
        area: areaNames.size,
        location: locationNames.size,
        unique: entries.size,
        autoGenerated: autoGeneratedCount,
        manual: manualCount,
        unmatched: unmatched.length,
      },
    },
    ...[...entries.values()].sort((a, b) => a.en.localeCompare(b.en)),
  ]

  await writeFile(OUTPUT_PATH, `${JSON.stringify(output, null, 2)}\n`, 'utf8')

  console.log(`Wrote ${OUTPUT_PATH}`)
  console.log(`area names: ${areaNames.size}`)
  console.log(`location names: ${locationNames.size}`)
  console.log(`dictionary entries: ${entries.size}`)
  console.log(`auto-generated: ${autoGeneratedCount}`)
  console.log(`manual: ${manualCount}`)

  if (unmatched.length > 0) {
    console.log(`unmatched (${unmatched.length}):`)
    unmatched.forEach((name) => console.log(` - ${name}`))
  }
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
